spring:
  datasource:
    generate-unique-name: false
    name: tacocloud
    url: jdbc:h2:mem:tacocloud
    driverClassName: org.h2.Driver
    username: sa
    password:

  data:
    rest:
      base-path: /data-api


taco:
  orders:
    pageSize: 0
